caltech_pedestrian:
  seq_dir: "./data/caltech_pedestrian/seq"
  vbb_dir: "./data/caltech_pedestrian/vbb"
  img_dir: "./data/caltech_pedestrian/images"
  ann_dir: "./data/caltech_pedestrian/annotations"

kaist_pedestrian:
  vbb_dir: "./data/vbb/train"
  img_dir: "./data/kaist_pedestrian/images/train"
  ann_dir: "./data/annotations"
