caltech_pedestrian:
  seq_dir: "./data/seq/caltech_pedestrian"
  vbb_dir: "./data/vbb/caltech_pedestrian"
  img_dir: "./data/images/caltech_pedestrian"
  ann_dir: "./data/annotations/caltech_pedestrian"

kaist_pedestrian:
  vbb_dir: "./data/vbb/kaist_pedestrian"
  img_dir: "./data/images/kaist_pedestrian"
  ann_dir: "./data/annotations/kaist_pedestrian"

